started synchronisation with beta100 repo

diff --git a/run b/run
--- a/run
+++ b/run
@@ -4,190 +4,90 @@
 
 function PrintUsage()
 {
-	echo -e "USAGE: run <option> <src file> <option> <dir> <dir> ..."
+	echo -e "USAGE: $0 <option> <src file> <option> <dir> <dir> ..."
 	echo -e "OPTIONS"
 
 	echo -e "	-h, --help		print this help and exit"
-	echo -e "	-no-run, -dno		do not run the program for any diagonal, just compile"
-	echo -e "	-d45b_56t, -d45b	run the program for diagonal 45b-56t"
-	echo -e "	-d45t_56b, -d45t	run the program for diagonal 45t-56b"
-	echo -e "	-dboth			run the program for both diagonals"
-	echo -e "	-dc, -dcomb		run the program in combined diagonals"
-	echo -e "	-danti			run the program in anti-diagonals"
+	echo -e "	-d <string>		select diagonals"
+	echo -e "	-dcomb			select 'combined' diagonal"
+	echo -e "	-danti			select anti-diagonals"
 	echo -e "	-O <option>		pass the option to the program"
-	echo -e "	-no-bckg		do no run compilation and programs in background"
-	echo -e "	-lxbatch		prepare job for LXBATCH instead of executing locally"
-	echo -e "	-submit			submit job to LXBATCH, implies -lxbatch option"
+	echo -e "	-wait			wait for all programs to finish"
+#	echo -e "	-batch			prepare job for LXBATCH instead of executing locally"
+#	echo -e "	-submit			submit job to LXBATCH, implies -lxbatch option"
 }
-
-#----------------------------------------------------------------------------------------------------
-
-diag_45b_56t="y"
-diag_45t_56b="y"
-diag_combined="y"
-
-diag_45b_56b="n"
-diag_45t_56t="n"
-
-runInBackground="y"
-pids=""
-
-lxbatch="n"
-submit="n"
-
-rcIncompatibleDiagonal=123
-
-bsub_options="pool>5000"
-bsub_queue="8nh"
-
-compileError="n"
 
 #----------------------------------------------------------------------------------------------------
 
 function RunOneDiagonal()
 {
-	local tag="$1"
-	local dir="$2"
-	local par_more="$3"
-	local diag="$4"
-	local options="$5"
-
 	local optionsStr=""
-	if [ ! "$options" == "" ]
+	if [ ! "$run_options" == "" ]
 	then
-		optionsStr=" ($options)"
+		optionsStr=" ($run_options)"
 	fi
 
 	label="$tag @ $dir:$diag"
-	log="${tag}_${diag}.log_run"
+	log="${tag}_${diag}.log"
 
-	if [ "$lxbatch" == "y" ]
-	then
-		local cwd=`pwd -P`
-		local job_dir="$cwd"
-		local job_file=".${tag}_${diag}.job"
-		local job_log_file=".${tag}_${diag}.log_job"
+	echo "$label > running$optionsStr"
+	{ time "$binDir/$bin" $run_options -dgn "$diag" ; } &> "$log"
+	errCode="$?"
+	case "$errCode" in
+		0)
+			echo "$label > done"
+			return 0
+			;;
 
-		cat "$top_dir/job_template" | sed "\
-				s|\$CMSSW_BASE|$CMSSW_BASE|; \
-				s|\$JOB_DIR|$job_dir|; \
-				s|\$JOB_LOG_FILE|$job_log_file|; \
-				s|\$COMMAND|{ time \"./$exe_file\" \"$diag\" $options ; } \&> \"$log\"|; \
-			" > "$job_file"
-		chmod u+x "$job_file"
+		$rcIncompatibleDiagonal)
+			rm "$log"
+			return 0
+			;;
 
-		if [ "$submit" == "y" ]
-		then
-			result=`bsub -R "$bsub_options" -q "$bsub_queue" -o /dev/null -e /dev/null "$cwd/$job_file"`
-			echo "$label > $result"
-		else
-			echo "$label > would be submitted (use -submit option)"
-		fi
-	else
-		echo "$label > running$optionsStr"
-		{ time "./$exe_file" "$diag" $options ; } &> "$log"
-		errCode="$?"
-		case "$errCode" in
-			0)
-				echo "$label > done"
-				return 0
-				;;
-
-			$rcIncompatibleDiagonal)
-				rm "$log"
-				return 0
-				;;
-
-			*)
-				echo "$label > run error ($errCode)"
-				if [ "$par_more" -eq 1 ]; then tail -n 5 "$log"; fi
-				return 1
-				;;
-		esac
-	fi
+		*)
+			echo "$label > run error ($errCode)"
+			tail -n 5 "$log"
+			return 1
+			;;
+	esac
 }
 
 #----------------------------------------------------------------------------------------------------
 
-function RunOneDir()
+function RunOneDirectory()
 {
-	local input="$1"
-	local src_file=".$input"
-	local tag="${input%.*}"
-	local exe_file=".$tag"
-	local dir="$2"
-	local par_more="$3"
-	local options="$4"
-
-	top_dir=`pwd`
-
-	cp "$input" "$dir/$src_file"
 	cd "$dir"
 
-	echo "$tag @ $dir > compiling"
-	g++ -O3 -Wall -Wextra -Wno-attributes --std=c++11 -g\
-			-I"$top_dir" \
-			`root-config --libs` -lMinuit -lMinuit2 `root-config --cflags` \
-			-I"$CMSSW_BASE/src" \
-			-I"$CMSSW_RELEASE_BASE/src" \
-			-L"$CMSSW_BASE/lib/slc7_amd64_gcc820" \
-			-L"$CMSSW_RELEASE_BASE/lib/slc7_amd64_gcc820" \
-			-lDataFormatsFWLite \
-			-lDataFormatsCommon \
-			-lDataFormatsCTPPSDetId \
-			-lDataFormatsCTPPSReco \
-			-I$GSL_DIR/include -L$GSL_DIR/lib -lgsl -lgslcblas -lm \
-			"$src_file" -o "$exe_file" &> "$tag.log_compile"
+	for prog in ${programs[*]}
+	do
+		tag="${prog%.*}"
+		bin=".$tag"
 
-	# compilation error?
- 	if [ $? -ne 0 ]
-	then
-		echo "$tag @ $dir > error in compilation"
-		if [ "$par_more" -eq 1 ]; then cat "$tag.log_compile"; fi
-		compileError="y"
-		return
-	else
-		echo "$tag @ $dir > compiled"
-	fi
+		for diag in ${diagonals[*]}
+		do
+			RunOneDiagonal &
+			pids="$pids $!"
+		done
+	done
 
-	if [ ! -s "$tag.log_compile" ]
-	then
-		rm "$tag.log_compile"
-	fi
-
-	# run
-	if [ "$diag_45b_56t" == "y" ]
-	then
-		RunOneDiagonal "$tag" "$dir" "$par_more" "45b_56t" "$options" &
-		pids="$pids $!"
-	fi
-
-	if [ "$diag_45t_56b" == "y" ]
-	then
-		RunOneDiagonal "$tag" "$dir" "$par_more" "45t_56b" "$options" &
-		pids="$pids $!"
-	fi
-
-	if [ "$diag_combined" == "y" ]
-	then
-		RunOneDiagonal "$tag" "$dir" "$par_more" "combined" "$options" &
-		pids="$pids $!"
-	fi
-
-	if [ "$diag_45b_56b" == "y" ]
-	then
-		RunOneDiagonal "$tag" "$dir" "$par_more" "45b_56b" "$options" &
-		pids="$pids $!"
-	fi
-
-	if [ "$diag_45t_56t" == "y" ]
-	then
-		RunOneDiagonal "$tag" "$dir" "$par_more" "45t_56t" "$options" &
-		pids="$pids $!"
-	fi
-
-	cd - &> /dev/null
+	cd - &>/dev/null
 }
+
+#----------------------------------------------------------------------------------------------------
+
+directories=()
+programs=()
+diagonals=("45b_56t" "45t_56b" "combined")
+
+run_options=""
+
+waitForPrograms="n"
+pids=""
+
+batch="n"
+submit="n"
+
+rcIncompatibleDiagonal=123
 
 #----------------------------------------------------------------------------------------------------
 
@@ -205,44 +105,17 @@ do
 			exit 1
 			;;
 
-		"-no-run" | "-dno")
-			diag_45b_56t="n"
-			diag_45t_56b="n"
-			diag_combined="n"
-			diag_45b_56b="n"
-			diag_45t_56t="n"
+		"-d")
+			shift
+			diagonals=($1)
 			;;
 
-		"-d45b_56t" | "-d45b")
-			diag_45b_56t="y"
-			diag_45t_56b="n"
-			diag_combined="n"
-			;;
-
-		"-d45t_56b" | "-d45t")
-			diag_45b_56t="n"
-			diag_45t_56b="y"
-			diag_combined="n"
-			;;
-
-		"-dboth")
-			diag_45b_56t="y"
-			diag_45t_56b="y"
-			diag_combined="n"
-			;;
-
-		"-dc" | "-dcomb")
-			diag_45b_56t="n"
-			diag_45t_56b="n"
-			diag_combined="y"
+		"-dcomb")
+			diagonals=("combined")
 			;;
 
 		"-danti")
-			diag_45b_56t="n"
-			diag_45t_56b="n"
-			diag_combined="n"
-			diag_45b_56b="y"
-			diag_45t_56t="y"
+			diagonals=("45b_56b" "45t_56t")
 			;;
 
 		"-O")
@@ -250,8 +123,8 @@ do
 			run_options="$1"
 			;;
 
-		"-no-bckg")
-			runInBackground="n"
+		"-wait")
+			waitForPrograms="y"
 			;;
 
 		"-lxbatch")
@@ -264,22 +137,17 @@ do
 			;;
 
 		*)
-			if [ ! -d "$1" ]
+			if [ -f "$1" ]
 			then
-				if [ -s "$1" ]
-				then
-					src_file="$1"
-				else
-					echo "ERROR: '$1' is neither source file, neither directory neither parameter."
-					PrintUsage
-					exit 1
-				fi
+				programs+=("$1")
 			else
-				if [ "$src_file" == "" ]
+				if [ -f "$1/config.py" ]
 				then
-					echo "ERROR: source file not defined, skipping directory '$1'."
+					directories+=("$1")
 				else
-					RunOneDir "$src_file" "$1" "1" "$run_options"
+					echo "ERROR: $1 is not understood."
+					PrintUsage
+					exit 2
 				fi
 			fi
 			;;
@@ -288,9 +156,25 @@ do
 	shift
 done
 
-if [ "$runInBackground" != "y" ]
+# compile all programs
+for prog in ${programs}
+do
+	target=".${prog%.*}"
+	make "$target" || exit 3
+done
+
+binDir=`pwd -P`
+
+# execute for directories
+for dir in ${directories[*]}
+do
+	RunOneDirectory
+done
+
+# wait for programs, if desired
+if [ "$waitForPrograms" == "y" ]
 then
-	error="$compileError"
+	error="n"
 
 	for p in $pids
 	do
